#!/bin/sh

set -u

DYNA_WRAPPER_INTERRUPTED=0
trap 'DYNA_WRAPPER_INTERRUPTED=1' INT

DYNA_WRAPPER_BEFORE=$(stty -g)
if "$@"; then
  DYNA_WRAPPER_STATUS=0
else
  DYNA_WRAPPER_STATUS=$?
fi
DYNA_WRAPPER_AFTER=$(stty -g)

printf '__DYNA_TTY_BEFORE__%s\n' "$DYNA_WRAPPER_BEFORE"
printf '__DYNA_TTY_AFTER__%s\n' "$DYNA_WRAPPER_AFTER"
printf '__DYNA_TTY_STATUS__%s\n' "$DYNA_WRAPPER_STATUS"
printf '__DYNA_TTY_INTERRUPTED__%s\n' "$DYNA_WRAPPER_INTERRUPTED"

exit "$DYNA_WRAPPER_STATUS"
