#!/bin/sh

set -eu

dyna_rule_result() {
  printf '{"schema":"dyna/cli-rule-status-v1","status":"%s","restartRequired":%s}\n' "$1" "$2"
}

dyna_rule_fail() {
  printf '{"schema":"dyna/cli-rule-status-v1","status":"error","code":"%s","message":"%s"}\n' "$1" "$2" >&2
  exit 1
}

if [ "$#" -ne 1 ]; then
  dyna_rule_fail "usage" "Pass exactly --check or --install."
fi

case "$1" in
  --check | --install)
    DYNA_RULE_MODE=$1
    ;;
  *)
    dyna_rule_fail "usage" "Pass exactly --check or --install."
    ;;
esac

DYNA_RULE_SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
DYNA_RULE_PLUGIN_ROOT=$(CDPATH= cd -- "$DYNA_RULE_SCRIPT_DIR/../../.." && pwd -P)
DYNA_RULE_LAUNCHER="$DYNA_RULE_PLUGIN_ROOT/bin/dyna"

if [ -L "$DYNA_RULE_LAUNCHER" ] || [ ! -f "$DYNA_RULE_LAUNCHER" ] || [ ! -x "$DYNA_RULE_LAUNCHER" ]; then
  dyna_rule_fail "invalid_launcher" "The installed Dyna launcher must be an executable regular file."
fi

DYNA_RULE_CODEX_INPUT=${CODEX_HOME:-"$HOME/.codex"}
if [ ! -d "$DYNA_RULE_CODEX_INPUT" ]; then
  if [ "$DYNA_RULE_MODE" = "--check" ]; then
    dyna_rule_result "missing" true
    exit 0
  fi
  umask 077
  mkdir -p -- "$DYNA_RULE_CODEX_INPUT"
fi
DYNA_RULE_CODEX_ROOT=$(CDPATH= cd -- "$DYNA_RULE_CODEX_INPUT" && pwd -P)

case "$DYNA_RULE_PLUGIN_ROOT/" in
  "$DYNA_RULE_CODEX_ROOT"/plugins/cache/*/)
    ;;
  *)
    dyna_rule_fail "not_installed" "Reconcile rules only from an installed FlowZone plugin cache."
    ;;
esac

case "$DYNA_RULE_LAUNCHER" in
  *'
'*)
    dyna_rule_fail "invalid_launcher" "The installed Dyna launcher path is unsupported."
    ;;
esac

DYNA_RULE_LAUNCHER_LITERAL=$(printf '%s' "$DYNA_RULE_LAUNCHER" | sed 's/\\/\\\\/g; s/"/\\"/g')
DYNA_RULE_DIRECTORY="$DYNA_RULE_CODEX_ROOT/rules"
DYNA_RULE_PATH="$DYNA_RULE_DIRECTORY/flowzone-dyna-worker.rules"

dyna_render_rule() {
  printf '%s\n' \
    '# Generated by the installed FlowZone Dyna skill. Re-run its reconciler after plugin updates.' \
    'prefix_rule(' \
    '    pattern = [' \
    "        \"$DYNA_RULE_LAUNCHER_LITERAL\"," \
    '        "item",' \
    '        ["show", "update", "enrich", "place", "archive", "restore"],' \
    '    ],' \
    '    decision = "allow",' \
    '    justification = "Allow the installed bounded Dyna item CLI to access the same-user local dashboard store.",' \
    ')' \
    '' \
    'prefix_rule(' \
    '    pattern = [' \
    "        \"$DYNA_RULE_LAUNCHER_LITERAL\"," \
    '        "follow-up",' \
    '        "create",' \
    '    ],' \
    '    decision = "allow",' \
    '    justification = "Allow the installed bounded Dyna CLI to create an explicitly requested linked follow-up.",' \
    ')' \
    '' \
    'prefix_rule(' \
    "    pattern = [\"$DYNA_RULE_LAUNCHER_LITERAL\", \"setup\"]," \
    '    decision = "allow",' \
    '    justification = "Allow the installed bounded Dyna CLI to verify the same-user local store.",' \
    ')'
}

DYNA_RULE_EXPECTED=$(dyna_render_rule)
if [ -e "$DYNA_RULE_PATH" ]; then
  if [ -L "$DYNA_RULE_PATH" ] || [ ! -f "$DYNA_RULE_PATH" ]; then
    dyna_rule_fail "invalid_rule_file" "The dedicated Dyna rule path must be a regular file."
  fi
  if [ "$(cat -- "$DYNA_RULE_PATH")" = "$DYNA_RULE_EXPECTED" ]; then
    dyna_rule_result "ready" false
    exit 0
  fi
fi

if [ "$DYNA_RULE_MODE" = "--check" ]; then
  if [ -e "$DYNA_RULE_PATH" ]; then
    dyna_rule_result "stale" true
  else
    dyna_rule_result "missing" true
  fi
  exit 0
fi

umask 077
mkdir -p -- "$DYNA_RULE_DIRECTORY"
if [ -L "$DYNA_RULE_DIRECTORY" ] || [ ! -d "$DYNA_RULE_DIRECTORY" ]; then
  dyna_rule_fail "invalid_rule_directory" "The Codex rules path must be a directory."
fi

DYNA_RULE_TEMP=$(mktemp "$DYNA_RULE_DIRECTORY/.flowzone-dyna-worker.rules.XXXXXX")
dyna_rule_cleanup() {
  rm -f -- "$DYNA_RULE_TEMP"
}
trap dyna_rule_cleanup 0 HUP INT TERM
dyna_render_rule >"$DYNA_RULE_TEMP"
chmod 600 "$DYNA_RULE_TEMP"
mv -f -- "$DYNA_RULE_TEMP" "$DYNA_RULE_PATH"
trap - 0 HUP INT TERM

dyna_rule_result "ready" true
